function Dcn = Dcn(q1,q2,q3,u1,u2,u3)
%DCN
%    DCN = DCN(Q1,Q2,Q3,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:21

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = cos(q3);
t7 = t2.*t3;
t15 = t4.*t5;
t8 = t7-t15;
t9 = t6.*t8;
t10 = sin(q3);
t11 = t2.*t5;
t12 = t3.*t4;
t13 = t11+t12;
t14 = t2.*t3.*2.0;
t17 = t10.*t13;
t16 = t9-t17;
t18 = t9+t14-t17-t4.*t5.*2.0;
t19 = t6.*t13;
t20 = t8.*t10;
t21 = t2.*t5.*2.0;
t22 = t3.*t4.*2.0;
t23 = t19+t20;
t24 = t23.*u3;
t25 = t19+t20+t21+t22;
t26 = t25.*u2;
Dcn = reshape([-t16.*u3-u1.*(t2.*2.0+t9+t14-t4.*t5.*2.0-t10.*t13)-u2.*(t9+t14-t4.*t5.*2.0-t10.*t13),0.0,t24+t26+u1.*(t4.*2.0+t19+t20+t21+t22),-t16.*u3-t18.*u1-t18.*u2,0.0,t24+t26+t25.*u1,-t16.*u1-t16.*u2-t16.*u3,0.0,t24+t23.*u1+t23.*u2,0.0,0.0,0.0],[3, 4]);
