function fj = fj(q1,q2,q3)
%FJ
%    FJ = FJ(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:24

fj = [q1.*(-1.0./1.0e1);q2.*(-1.0./1.0e1);q3.*(-1.0./1.0e1);0.0];
