function rc = rc(q1,q2,q3,q4)
%RC
%    RC = RC(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:23

t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = cos(q2);
t6 = t2.*2.0;
t7 = t2.*t5;
t8 = cos(q3);
t9 = t2.*t4;
t10 = t3.*t5;
t11 = t9+t10;
t12 = sin(q3);
t13 = t7-t3.*t4;
t14 = sin(q4);
t15 = cos(q4);
rc = reshape([t2,t6+t7-t3.*t4,t6+t2.*t5.*2.0-t3.*t4.*2.0+t8.*t13-t11.*t12,t6+t2.*t15-t3.*t14,0.0,0.0,0.0,0.0,-t3,t3.*-2.0-t2.*t4-t3.*t5,t3.*-2.0-t2.*t4.*2.0-t3.*t5.*2.0-t8.*t11-t12.*t13,t3.*-2.0-t2.*t14-t3.*t15],[4, 3]);
