function rj = rj(q1,q2,q3,q4)
%RJ
%    RJ = RJ(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:23

t2 = cos(q1);
t3 = t2.*2.0;
t4 = sin(q1);
t5 = sin(q2);
t6 = cos(q2);
t7 = t2.*t6.*2.0;
t8 = cos(q3);
t9 = t2.*t5;
t10 = t4.*t6;
t11 = t9+t10;
t12 = sin(q3);
t13 = t2.*t6;
t14 = t13-t4.*t5;
t15 = sin(q4);
t16 = cos(q4);
rj = reshape([0.0,t3,t3+t7-t4.*t5.*2.0,t3,t3+t7-t4.*t5.*2.0+t8.*t14-t11.*t12,t3+t2.*t16-t4.*t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4.*-2.0,t4.*-2.0-t2.*t5.*2.0-t4.*t6.*2.0,t4.*-2.0,t4.*-2.0-t2.*t5.*2.0-t4.*t6.*2.0-t8.*t11-t12.*t14,t4.*-2.0-t2.*t15-t4.*t16,0.0,0.0,0.0,1.0,3.0,4.0],[6, 4]);
