function Tef = Tef(q1,q2,q3)
%TEF
%    TEF = TEF(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:22

t2 = sin(q1);
t3 = cos(q1);
t4 = sin(q2);
t5 = cos(q2);
t6 = cos(q3);
t7 = t3.*t4;
t8 = t2.*t5;
t9 = t7+t8;
t10 = sin(q3);
t11 = t2.*t4;
t13 = t3.*t5;
t12 = t10.*(t11-t13);
t14 = t2.*t4.*2.0;
t15 = t6.*(t11-t13);
t16 = t9.*t10;
Tef = reshape([t2.*-2.0+t12-t2.*t5.*2.0-t3.*t4.*2.0-t6.*t9,0.0,t3.*-2.0+t14+t15+t16-t3.*t5.*2.0,t12-t2.*t5.*2.0-t3.*t4.*2.0-t6.*t9,0.0,t14+t15+t16-t3.*t5.*2.0,t12-t6.*t9,0.0,t15+t16,0.0,0.0,0.0],[3, 4]);
