function vc = vc(q1,q2,q3,q4,u1,u2,u3,u4)
%VC
%    VC = VC(Q1,Q2,Q3,Q4,U1,U2,U3,U4)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Oct-2014 05:35:23

t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = t2.*t4;
t6 = cos(q2);
t7 = t3.*t6;
t8 = t3.*t4;
t9 = t3.*2.0;
t10 = t5+t7;
t11 = t2.*t6;
t12 = cos(q3);
t13 = t10.*t12;
t14 = sin(q3);
t15 = t8-t11;
t16 = t2.*t4.*2.0;
t17 = t3.*t6.*2.0;
t18 = t2.*2.0;
t19 = t12.*t15;
t20 = t10.*t14;
t21 = t3.*t4.*2.0;
t22 = sin(q4);
t23 = t2.*t22;
t24 = cos(q4);
t25 = t3.*t24;
t26 = t3.*t22;
vc = reshape([-t3.*u1,-t10.*u2-u1.*(t5+t7+t9),-u1.*(t9+t13+t16+t17-t14.*t15)-u2.*(t13+t16+t17-t14.*t15)-u3.*(t13-t14.*t15),-u4.*(t23+t25)-u1.*(t9+t23+t25),0.0,0.0,0.0,0.0,-t2.*u1,u2.*(t8-t2.*t6)-u1.*(-t8+t11+t18),u3.*(t19+t20)+u1.*(-t18+t19+t20+t21-t2.*t6.*2.0)+u2.*(t19+t20+t21-t2.*t6.*2.0),-u1.*(t18-t26+t2.*t24)+u4.*(t26-t2.*t24)],[4, 3]);
