function fj = fj(q2,q3,q4,u2,u3,u4)
%FJ
%    FJ = FJ(Q2,Q3,Q4,U2,U3,U4)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Jul-2015 14:28:01

fj = [0.0;-q2-u2;-q3-u3;-q4-u4];
