function Tef = Tef
%TEF
%    TEF = TEF

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Jul-2015 14:28:01

Tef = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 4]);
