function fj = fj
%FJ
%    FJ = FJ

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    01-Oct-2014 21:43:10

fj = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
