function rc = rc(q1,q2,q3)
%RC
%    RC = RC(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    24-Jul-2014 13:59:43

t2 = cos(q1);
t3 = q1+q2;
t4 = sin(q1);
t5 = cos(t3);
t6 = t2.*2.0;
t7 = q1+q2+q3;
t8 = sin(t3);
rc = reshape([t2,t5+t6,t5.*2.0+t6+cos(t7),0.0,0.0,0.0,-t4,t4.*-2.0-t8,t4.*-2.0-t8.*2.0-sin(t7)],[3, 3]);
