function vc = vc(q1,q2,q3,u1,u2,u3)
%VC
%    VC = VC(Q1,Q2,Q3,U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    24-Jul-2014 13:59:43

t2 = sin(q1);
t3 = q1+q2;
t4 = sin(t3);
t5 = cos(q1);
t6 = cos(t3);
t7 = q1+q2+q3;
t8 = sin(t7);
t9 = t4.*2.0;
t10 = t2.*2.0;
t11 = cos(t7);
t12 = t6.*2.0;
t13 = t5.*2.0;
vc = reshape([-t2.*u1,-u1.*(t4+t10)-t4.*u2,-u2.*(t8+t9)-t8.*u3-u1.*(t8+t9+t10),0.0,0.0,0.0,-t5.*u1,-u1.*(t6+t13)-t6.*u2,-u2.*(t11+t12)-t11.*u3-u1.*(t11+t12+t13)],[3, 3]);
