function wc = wc(u1,u2,u3)
%WC
%    WC = WC(U1,U2,U3)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    24-Jul-2014 13:59:43

wc = reshape([0.0,0.0,0.0,u1,u1+u2,u1+u2+u3,0.0,0.0,0.0],[3, 3]);
