function fj = fj
%FJ
%    FJ = FJ

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Oct-2014 17:34:05

fj = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
