function rc = rc(q1,q2,q3,q4,q5)
%RC
%    RC = RC(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Oct-2014 17:34:06

t2 = cos(q1);
t3 = cos(q3);
t4 = sin(q1);
t5 = cos(q2);
t6 = sin(q3);
t7 = sin(q2);
t8 = sin(q5);
t9 = sin(q4);
t10 = cos(q4);
t11 = cos(q5);
t12 = t3.*t4;
t13 = t2.*t5.*t6;
rc = [t2+t8.*(t10.*(t2.*t6+t3.*t4.*t5)-t4.*t7.*t9)-t11.*(t2.*t3-t4.*t5.*t6)-t2.*t3+t4.*t5.*t6+1.0,-t8.*(t5.*t9+t3.*t7.*t10)-t6.*t7-t6.*t7.*t11,-t4+t12+t13+t11.*(t12+t13)-t8.*(t10.*(t4.*t6-t2.*t3.*t5)+t2.*t7.*t9)];
