function rj = rj(q1,q2,q3)
%RJ
%    RJ = RJ(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Oct-2014 17:34:05

t2 = cos(q1);
t3 = sin(q3);
t4 = sin(q1);
t5 = cos(q3);
t6 = cos(q2);
rj = [t2-t2.*t5+t3.*t4.*t6+1.0,-t3.*sin(q2),-t4+t4.*t5+t2.*t3.*t6,0.0];
