function vc = vc(q1,q2,q3,q4,q5,u1,u2,u3,u4,u5)
%VC
%    VC = VC(Q1,Q2,Q3,Q4,Q5,U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    02-Oct-2014 17:34:05

t2 = sin(q1);
t3 = cos(q1);
t4 = cos(q3);
t5 = cos(q2);
t6 = sin(q3);
t7 = sin(q5);
t8 = cos(q4);
t9 = sin(q2);
t10 = sin(q4);
t11 = cos(q5);
t12 = t2.*t4;
t13 = t3.*t5.*t6;
t14 = t3.*t6;
t15 = t2.*t4.*t5;
t16 = t14+t15;
t17 = t3.*t4;
t28 = t2.*t5.*t6;
t18 = t17-t28;
t19 = t2.*t6;
t25 = t3.*t4.*t5;
t20 = t19-t25;
t21 = t8.*t20;
t22 = t3.*t9.*t10;
t23 = t21+t22;
t24 = t12+t13;
t26 = t8.*t16;
t27 = t26-t2.*t9.*t10;
vc = [u3.*(t14+t15+t11.*t16+t7.*t8.*t18)-u2.*(t7.*(t2.*t5.*t10+t2.*t4.*t8.*t9)+t2.*t6.*t9+t2.*t6.*t9.*t11)+u1.*(-t2+t12+t13-t7.*t23+t11.*t24)+u5.*(t7.*t18+t11.*t27)-t7.*u4.*(t10.*t16+t2.*t8.*t9),-u5.*(t11.*(t5.*t10+t4.*t8.*t9)-t6.*t7.*t9)-u3.*(t4.*t9+t4.*t9.*t11-t6.*t7.*t8.*t9)-u2.*(-t7.*(t9.*t10-t4.*t5.*t8)+t5.*t6+t5.*t6.*t11)-t7.*u4.*(t5.*t8-t4.*t9.*t10),-u2.*(t7.*(t3.*t5.*t10+t3.*t4.*t8.*t9)+t3.*t6.*t9+t3.*t6.*t9.*t11)-u1.*(t3-t17+t28-t11.*t18+t7.*t27)-u3.*(t19-t25+t11.*t20+t7.*t8.*t24)-u5.*(t7.*t24+t11.*t23)+t7.*u4.*(t10.*t20-t3.*t8.*t9)];
